version: "3"
services:

  fe:
    build: ./auth-zero-fe/
    container_name: "react_fe"
    ports:
      - "80:80"

  be:
    build: ./auth-zero-be/
    container_name: "node_be"
    env_file:
      - ./auth-zero-be/docker.env
      - ./db/pg/docker.env
      - ./db/mongo/docker.env
    ports:
      - "3001:3001"
    depends_on: 
      - pgdb

  mongo:
    image: "mongo:3.4.23"
    container_name: "mongo"
    env_file: 
      - ./db/mongo/docker.env
    ports: 
      - "27017:27017"
    volumes:
      - ./db/mongo/:/docker-entrypoint-initdb.d/

  mongo-express:
    image: "mongo-express" 
    container_name: "mongo-express"
    env_file: 
      - ./db/mongo/docker.env
    ports:
      - "8081:8081"

  pgdb:
    image: "postgres:12.1-alpine"
    container_name: "pgdb"
    env_file: 
      - ./db/pg/docker.env
    container_name: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./db/pg/:/docker-entrypoint-initdb.d/