version: "3"
services:

  fe:
    build: ./auth-zero-fe/
    ports:
      - "80:80"

  be:
    build: ./auth-zero-be/
    env_file:
      - ./auth-zero-be/docker.env
    ports:
      - "3001:3001"

  mongo:
    image: "mongo:3.4.23"
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./db/mongo/:/docker-entrypoint-initdb.d/

  mongo-express:
    image: "mongo-express" 
    ports:
      - "8081:8081"
    environment: 
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  postgres:
    image: "postgres:12.1-alpine"
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test1234
      - POSTGRES_DB=test_db
    container_name: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgres
      - ./db/pg/:/docker-entrypoint-initdb.d/